# Generated by Django 3.2.6 on 2021-08-22 19:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SinglePageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование страницы')),
                ('icon', models.CharField(blank=True, choices=[('<i class="icon-realestate-washing-machine"></i>', 'Стиралка'), ('<i class="icon-realestate-window"></i>', 'Окно'), ('<i class="icon-realestate-tools"></i>', 'Инструменты'), ('<i class="icon-realestate-box"></i>', 'Коробки')], default='Freshman', max_length=250, verbose_name='Иконки')),
                ('slug', models.SlugField(max_length=70, unique=True, verbose_name='Наименование урла')),
                ('content', models.TextField(verbose_name='Текст статьи')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
