# Generated by Django 3.2.6 on 2021-08-24 19:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SinglePages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlepagemodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 19, 15, 37, 921023, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='singlepagemodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
