# Generated by Django 3.2.6 on 2021-08-24 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SinglePages', '0002_auto_20210824_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlepagemodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 19, 46, 19, 203956, tzinfo=utc)),
        ),
    ]
