# Generated by Django 3.2.6 on 2021-08-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SinglePages', '0004_alter_singlepagemodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlepagemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
