# Generated by Django 3.2.6 on 2021-08-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
