# Generated by Django 3.2.6 on 2021-08-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210823_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocksforservicemodel',
            options={'ordering': ['id'], 'verbose_name': 'Категория в block', 'verbose_name_plural': 'Категории в block'},
        ),
    ]
