# Generated by Django 3.2.6 on 2021-08-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_blocksforservicemodel_block_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocksforservicemodel',
            options={'ordering': ['id'], 'verbose_name': 'Модули для страниц', 'verbose_name_plural': 'Модули для страниц'},
        ),
        migrations.AlterField(
            model_name='blocksforservicemodel',
            name='block_price',
            field=models.TextField(blank=True, verbose_name='Блок с расчетом стоимости'),
        ),
    ]
