# Generated by Django 3.2.6 on 2021-08-30 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_auto_20210821_1145'),
        ('service', '0014_alter_comment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicemodel')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_taggedservice_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FirstPageServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Текст статьи')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('tables', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.blocksforservicemodel', verbose_name='Таблицы')),
            ],
            options={
                'verbose_name': 'Главная страница в сервисе (страница категории)',
                'verbose_name_plural': 'Главная страница в сервисе (страница категории)',
                'ordering': ['id'],
            },
        ),
    ]
