# Generated by Django 3.2.6 on 2021-08-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_alter_firstpageservicemodel_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstpageservicemodel',
            name='tables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.blocksforservicemodel', verbose_name='Таблицы'),
        ),
    ]
