# Generated by Django 3.2.6 on 2021-08-31 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_alter_firstpageservicemodel_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstpageservicemodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='firstpageservicemodel',
            name='content',
        ),
        migrations.RemoveField(
            model_name='firstpageservicemodel',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='firstpageservicemodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='firstpageservicemodel',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='firstpageservicemodel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='firstpageservicemodel',
            name='tables',
        ),
        migrations.RemoveField(
            model_name='firstpageservicemodel',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='firstpageservicemodel',
            name='time_update',
        ),
    ]
