# Generated by Django 3.2.6 on 2021-08-31 12:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_auto_20210831_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstpageservicemodel',
            options={'ordering': ['id'], 'verbose_name': 'Главная страница в сервисе (страница категории)', 'verbose_name_plural': 'Главная страница в сервисе (страница категории)'},
        ),
        migrations.AddField(
            model_name='firstpageservicemodel',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст статьи'),
        ),
        migrations.AddField(
            model_name='firstpageservicemodel',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AddField(
            model_name='firstpageservicemodel',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstpageservicemodel',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstpageservicemodel',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstpageservicemodel',
            name='tables',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='service.blocksforservicemodel', verbose_name='Таблицы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstpageservicemodel',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstpageservicemodel',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
    ]
