# Generated by Django 3.2.6 on 2021-08-31 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callback',
            options={'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
    ]
